server.port=8080
spring.main.web-application-type=servlet

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./dealer_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=false
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# MyBatis 映射文件位置
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=com.dealer.entity
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true


spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
# ======================
# 日志配置（必生成文件）
# ======================
logging.file.name=./run.log
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.dealer=DEBUG

# 日志格式
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
